### PR TITLE
fix: update golang version in 1.21.3

### PR DESCRIPTION
**Pull request by jplanckeel**
# Context

In the goal to have no security issue on this projet. Upgrade Golang to the last version. 

# Test

- Build ipmi-exporter
- Run impi exporter

### CODE REVIEW

**Comment by Raskyld** [comment]
Was there any BC that could affect the codebase ?

**Comment by SuperQ** [comment]
This is not how we update Go in Prometheus projects. Your changes have no effect this way.

**Comment by jplanckeel** [comment]
> This is not how we update Go in Prometheus projects. Your changes have no effect this way.

Hello, no problem have you a documentation for this ?

**Comment by SuperQ** [comment]
No, sorry, we don't have good documentation for this. I've been wanting to setup something like renovate bot to do these updates.

**Pull request closed without merging**
