### PR TITLE
Update for Prometheus Community

### PR DESCRIPTION
**Pull request by SuperQ**
* Update Makefile.common from prometheus/prometheus.
* Switch from Cirrus to CircleCI.
* Add CHANGELOG.md and VERSION.
* Drop inline /vendor.
* Update references to old github URL.
* Update copyrights.
* Update Go version.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by bitfehler** [comment]
Thanks a bunch for doing this!!

Minor thing: can we set the version to something that makes it not go backwards?

**Comment by bitfehler** [comment]
BTW, can you grant me merge access? I currently don't have it anymore

**Comment by SuperQ** [comment]
I extracted the CHANGELOG from the GitHub releases API.

**Review by bitfehler — APPROVED** [review]
:shipit: :rainbow: :100:

**Pull request merged**
