### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by SuperQ**
* Update Go to 1.21.
* Update minimum Go version to 1.19.
* Fixup deprecated `io/ioutil`.
* Move errcheck excludes inline.

### CODE REVIEW

**Comment by jplanckeel** [comment]
Hi, this is the first time I've contributed here but I don't think it's cool to close the MR without any info and open one in // for this. 

We could have made this one evolve to reach the desired standard. 

https://github.com/prometheus-community/ipmi_exporter/pull/169  

Thanks in any case for the update.

**Review by sysadmind — APPROVED** [review]
LGTM

**Comment by jplanckeel** [comment]
Hello, it's possible to create a release ?

**Comment by SuperQ** [comment]
@jplanckeel Sure, would you like to help with this? You would need to edit the CHANGELOG.md and VERSION files.

We generally only list the user visible changes, not mechanical updates like Go versions or other maintenance PRs.

**Comment by jplanckeel** [comment]
there have been quite a few version upgrades of GO and deps, this could be a good thing.  In addition, it would provide users with a tag other than latest or master for their production. 

I'll prepare the MR for you. You're more in favor of a fix or minor bump

**Comment by jplanckeel** [comment]
The PR : https://github.com/prometheus-community/ipmi_exporter/pull/173

Thank you 👍

**Pull request merged**
